# Application setup
swagger: "2.0"
info:
  title: A find great study spots application
  version: 1.0.0
  description: The best application
definitions: 
# Model
  spots:
    type: object
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
        minLength: 1
      location:
        type: string
        minLength: 1
      tags:
        type: string
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
# Endpoint
paths:
  /:
    get:
      tags:
        - spots
      parameters:
        - name: since
          in: query
          type: integer
          format: int64
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: list the spot operations
          schema:
            type: array
            items:
              $ref: "#/definitions/spots"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
